"""Add expire_date to FreeConfig

Revision ID: 0cdb203b547a
Revises: b962ea00b918
Create Date: 2026-04-17 03:05:06.740774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdb203b547a'
down_revision: Union[str, Sequence[str], None] = 'b962ea00b918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free_configs', sa.Column('expire_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free_configs', 'expire_date')
    # ### end Alembic commands ###
