"""Add product pricing and active toggles

Revision ID: 72e5e98ffed5
Revises: cec6b98d5ffd
Create Date: 2026-04-12 04:27:16.158892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e5e98ffed5'
down_revision: Union[str, Sequence[str], None] = 'cec6b98d5ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('price_usd', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'price_usd')
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
