"""Add missing fields to FreeConfig

Revision ID: b2db7334e8c4
Revises: e6c8e7db1c59
Create Date: 2026-04-17 02:40:52.774742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2db7334e8c4'
down_revision: Union[str, Sequence[str], None] = 'e6c8e7db1c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free_configs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('free_configs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('free_configs', sa.Column('config_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free_configs', 'config_data')
    op.drop_column('free_configs', 'description')
    op.drop_column('free_configs', 'country')
    # ### end Alembic commands ###
