"""Add title to FreeConfig

Revision ID: b962ea00b918
Revises: b2db7334e8c4
Create Date: 2026-04-17 02:56:14.708513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b962ea00b918'
down_revision: Union[str, Sequence[str], None] = 'b2db7334e8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free_configs', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free_configs', 'title')
    # ### end Alembic commands ###
