"""Add crypto networks and receipt type

Revision ID: cec6b98d5ffd
Revises: 3a8f0c1e8ef9
Create Date: 2026-04-12 03:58:31.376146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec6b98d5ffd'
down_revision: Union[str, Sequence[str], None] = '3a8f0c1e8ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('receipts', sa.Column('receipt_type', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('reference_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'reference_id')
    op.drop_column('receipts', 'receipt_type')
    op.drop_table('crypto_networks')
    # ### end Alembic commands ###
