"""phase5

Revision ID: e6c8e7db1c59
Revises: 72e5e98ffed5
Create Date: 2026-04-12 04:59:43.776764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c8e7db1c59'
down_revision: Union[str, Sequence[str], None] = '72e5e98ffed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_text', sa.String(length=500), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('expire_date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.drop_column('products', 'price_usd')
    op.add_column('tickets', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'department')
    op.add_column('products', sa.Column('price_usd', sa.FLOAT(), nullable=True))
    op.drop_column('products', 'duration_days')
    op.drop_column('orders', 'expire_date')
    op.drop_table('free_configs')
    # ### end Alembic commands ###
